---
title: "Misc"
author: "VadimTk"
date: "April 7, 2016"
--output: html_document
output:
  md_document:
    variant: markdown_github

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("RMySQL")
library(stringr)
library(ggplot2)
library(ggthemes)
library(reshape2)
library(knitr)

tm<-theme(legend.position="bottom",
          text=element_text(family="Georgia"),
          strip.background = element_rect(colour="red", fill="#CCCCFF"))

guides(colour = guide_legend(override.aes = list(size=4)))


cons <- dbListConnections(MySQL())
for(con in cons)
    dbDisconnect(con)
con <- dbConnect(MySQL(), user="sbtest", dbname="benchmarks", host="10.20.2.4")

```


## Power and governors 

```{r power, echo=FALSE, fig.height=6, fig.width=8, warning=FALSE}
title <- "[local] sysbench OLTP IO memory"
p2 = dbGetQuery( con,'select sr.runid runidfull,sr.threads, avg(tps) tps, STDDEV_POP(tps) se,avg(rt) rt, STDDEV_POP(rt) sert
                 from sbtest_results sr,(select runid,threads from sbtest_results where (runid like "OLTP-IO-RO-power#%") group by runid,threads having count(*) > 10) t 
                 where sec>100 and sec<600 and (sr.runid like "OLTP-IO-RO-power%")
                 and sr.runid=t.runid and sr.threads=t.threads GROUP BY sr.runid, sr.threads
                 ' )
p2$runid <- str_extract(p2$runidfull, "([^#]*)$")

aggdata <-aggregate(p2, by=list(p2$runid,p2$threads),FUN=mean, na.rm=TRUE)
t1<-dcast(aggdata,threads~Group.1,mean,value.var = "tps")
kable(t1, digits=2)
ss=subset(p2)
m <- ggplot(ss, aes(x=as.factor(threads),y=as.numeric(tps),color=runid,group=runid))
m+geom_line()+geom_errorbar(aes(ymin=tps-se, ymax=tps+se),width=0.15)+labs(x="Threads",y="Throughput,tps",title=title)+scale_color_tableau(name="Version")+scale_y_continuous(breaks=seq(0, 21000, 1000),labels = scales::comma,limits=c(0,21000))+theme(axis.text.x  = element_text(angle=45, vjust=0.5))+tm


```




